micronaut:
  server:
    port: 8082
  application:
    name: customerservice
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**



datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    dialect: POSTGRES
    auto-commit: true
    maximum-pool-size: 50
    minimum-idle: 2
    idle-timeout: 600000
    data-source-properties:
     reWriteBatchInserts: true
     disableColumnSanitiser: true

jpa:
  default:
    entity-scan:
      packages: 'com.psl'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true

endpoints:
  health:
    enabled: true